[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "my-cool-django-app"
version = "42"
dependencies = [
    "accelerate",
    "aiohappyeyeballs",
    "aiohttp",
    "aiosignal",
    "annotated-doc",
    "annotated-types",
    "anthropic",
    "antlr4-python3-runtime",
    "anyio",
    "attrs",
    "audioread",
    "beautifulsoup4",
    "blinker",
    "bracex",
    "cachetools",
    "certifi",
    "cffi",
    "charset-normalizer",
    "click",
    "coloredlogs",
    "colorlog",
    "dataclasses-json",
    "decorator",
    "deepagents",
    "dill",
    "distro",
    "dnspython",
    "docling",
    "docling-core",
    "docling-ibm-models",
    "docling-parse",
    "docstring_parser",
    "et_xmlfile",
    "Faker",
    "filelock",
    "filetype",
    "FlashRank",
    "Flask",
    "Flask-HTTPAuth",
    "flatbuffers",
    "frozenlist",
    "fsspec",
    "google-api-python-client",
    "google-auth",
    "google-auth-oauthlib",
    "google-genai",
    "greenlet",
    "grpcio",
    "h11",
    "hf-xet",
    "httpcore",
    "httpx",
    "httpx-sse",
    "huggingface_hub",
    "humanfriendly",
    "idna",
    "itsdangerous",
    "Jinja2",
    "jiter",
    "joblib",
    "jsonlines",
    "jsonpatch",
    "jsonpointer",
    "jsonref",
    "jsonschema",
    "jsonschema-specifications",
    "langchain",
    "langchain-anthropic",
    "langchain-classic",
    "langchain-community",
    "langchain-core",
    "langchain-google-genai",
    "langchain-mcp-adapters",
    "langchain-milvus",
    "langchain-openai",
    "langchain-text-splitters",
    "langgraph",
    "langgraph-checkpoint",
    "langgraph-prebuilt",
    "langgraph-sdk",
    "langsmith",
    "latex2mathml",
    "lazy-loader",
    "librosa",
    "llvmlite",
    "lxml",
    "markdown-it-py",
    "marko",
    "MarkupSafe",
    "marshmallow",
    "mdurl",
    "milvus-lite",
    "ml_dtypes",
    "mpire",
    "mpmath",
    "msgpack",
    "multidict",
    "multiprocess",
    "mypy_extensions",
    "networkx",
    "numba",
    "numpy",
    "omegaconf",
    "onnx",
    "onnxruntime",
    "openai",
    "opencv-python",
    "opencv-python-headless",
    "openpyxl",
    "orjson",
    "ormsgpack",
    "packaging",
    "pandas",
    "pdfminer",
    "pillow",
    "platformdirs",
    "pluggy",
    "polyfactory",
    "pooch",
    "propcache",
    "protobuf",
    "psutil",
    "pyasn1",
    "pyasn1_modules",
    "pyclipper",
    "pycparser",
    "pycryptodome",
    "pydantic",
    "pydantic-settings",
    "pydantic_core",
    "Pygments",
    "PyJWT",
    "pylatexenc",
    "pymilvus",
    "pymongo",
    "pypdfium2",
    "python-dateutil",
    "python-docx",
    "python-dotenv",
    "python-pptx",
    "pytz",
    "PyYAML",
    "rapidocr",
    "referencing",
    "regex",
    "requests",
    "requests-toolbelt",
    "rich",
    "rpds-py",
    "rsa",
    "rtree",
    "safetensors",
    "scikit-learn",
    "scipy",
    "semchunk",
    "shapely",
    "shellingham",
    "six",
    "sniffio",
    "soundfile",
    "soupsieve",
    "soxr",
    "SQLAlchemy",
    "sympy",
    "tabulate",
    "tavily-python",
    "tenacity",
    "threadpoolctl",
    "tiktoken",
    "tokenizers",
    "torch",
    "torchvision",
    "tqdm",
    "transformers",
    "typer",
    "typing-inspect",
    "typing-inspection",
    "typing_extensions",
    "tzdata",
    "urllib3",
    "uuid_utils",
    "wcmatch",
    "websockets",
    "Werkzeug",
    "xlsxwriter",
    "xxhash",
    "yarl",
    "zstandard",
]

[project.optional-dependencies]
dev = ["pytest"]
